# -*- coding: utf-8 -*-
"""Filmes_dataframe_PedroOliveira_D3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p4BmM4Y0rX7fw6yvn4h7pH4nk6LxIb76

#Questão 1
"""

import pandas as pd

# Dados das filmes
nome_filme = ["Interestelar", "Ilha do Medo", "A Chegada", "Clube da Luta", "Bastardos Inglórios", "Corra!"]
diretor = ["Christopher Nolan", "Martin Scorsese", "Denis Villeneuve", "David Fincher", "Quentin Tarantino", "Jordan Peele"]
generos = ["Ficção Científica", "Suspense · drama", "Ficção científica · Mistério", "Suspense · Ação", "Guerra · Aventura", "Terror · Comédia"]
ano_lancamento = [2014, 2010, 2016, 1999, 2009, 2017]
estudio = ["Paramount Pictures", "Paramount Pictures", "21 Laps Entertainment", "20th Century Studios", "The Weinstein Company", "Blumhouse Productions"]
tempo_duração = [2.49, 2.18, 1.56, 2.19, 2.33, 1.44]

# Crie um dicionário contendo dados dos filmes
dados_filmes = {
    'Nome do Filme': nome_filme,
    'Diretor': diretor,
    'Genero': generos,
    'Ano de lançamento': ano_lancamento,
    'Estudio': estudio,
    'Duração' : tempo_duração
}

# Crie um DataFrame a partir do dicionário
pedro_D3_filmes_df = pd.DataFrame(dados_filmes)
print(pedro_D3_filmes_df)

print()

# Exibir o DataFrame
display(pedro_D3_filmes_df)

"""#Questão 2"""

#--2 Apresente o tamanho do seu dataframe (quantas colunas x linhas).
print(f"Tamanho do DataFrame: {pedro_D3_filmes_df.shape[0]} linhas x {pedro_D3_filmes_df.shape[1]} colunas")

"""#Questão 3"""

#--3 Acesse a linha (x) e apresente em tela todas as características do item.
x = 4
item = pedro_D3_filmes_df.iloc[x]
print(f"\nCaracterísticas do item na linha {x}:")
print(item)

"""#Questão 4"""

#--4 Verifique se o dataframe está vazio.
if pedro_D3_filmes_df.empty:
    print("O DataFrame está vazio.")
else:
    print("O DataFrame não está vazio.")

"""#Questão 5"""

#--5 Apresente em tela os 5 primeiros registros da base de dados.
print("\nOs 5 primeiros registros do DataFrame:")
print(pedro_D3_filmes_df.head())

display(pedro_D3_filmes_df.head())

"""#Questão 6"""

#--6 Exclua um item (linha) de sua base de dados.
linha_para_excluir = 2
pedro_D3_filmes_df = pedro_D3_filmes_df.drop(linha_para_excluir).reset_index(drop=True)

"""#Questão 7"""

#--7 Adicione um item (linha) na sua base de dados.
novo_filme = {
    'Nome do Filme': "Não Olhe para Cima",
    'Diretor': "Adam McKay",
    'Genero': "Comédia/Ficção científica",
    'Ano de lançamento': 2021,
    'Estudio': "Hyperobject Industries",
    'Duração (Horas)': 2.25
}

pedro_D3_filmes_df.loc[pedro_D3_filmes_df.shape[0]] = novo_filme
print("\nDataFrame após a adição de uma nova linha:")
print(pedro_D3_filmes_df)

display(pedro_D3_filmes_df)

print(f"\nTamanho do DataFrame após a adição: {pedro_D3_filmes_df.shape[0]} linhas x {pedro_D3_filmes_df.shape[1]} colunas")

"""#Questão 8"""

#--8 Transponha a coluna para a linha em sua base de dados.
pedro_D3_filmes_df_transposto = pedro_D3_filmes_df.transpose()

print("\nDataFrame transposto:")
print(pedro_D3_filmes_df_transposto)
display(pedro_D3_filmes_df_transposto)
print(f"\nTamanho do DataFrame transposto: {pedro_D3_filmes_df_transposto.shape[0]} linhas x {pedro_D3_filmes_df_transposto.shape[1]} colunas")

"""#Questão 9"""

#--9 Apresente em tela somente a 1ª e a 2ª coluna (rótulo) da base de dados.
print("\nSomente a 1ª e a 2ª coluna do DataFrame:")
print(pedro_D3_filmes_df[['Nome do Filme', 'Diretor']])
display(pedro_D3_filmes_df[['Nome do Filme', 'Diretor']])

"""#Questão 10"""

#--10
print("\nO projeto foi desenvolvido com base em uma das indústrias de entretenimento das quais eu mais gosto: a cinematográfica!",
"\nColetei os dados disponíveis na web em sites focados na indútria cinematográfica, e também nos meus conhecimentos \nprévios sobre os filmes catalogados, pois são os meus preferidos!",
"\nA linguagem de programação utilizada neste projeto foi o Python, e a IDE utilizada foi o Googel Colabority.")